trigger:
- main

pool:
  name: 'Default'

steps:
- checkout: self
  displayName: "Récupération du code de structure de GitHub"

- script: |
    echo === Configuration locale de l environnement Java ===
    REM On force l agent a connaitre le chemin de votre Java JRE
    set JAVA_HOME=C:\SQL Developer\sqldeveloper-26.2.0.186.2220-x64\sqldeveloper\jdk\jre
    set PATH=%JAVA_HOME%\bin;%PATH%
    
    echo === Debut du deploiement automatise Oracle ===
    echo Connexion a la PDB pdb1 sur la VM Linux en cours...
    
    REM Appel de l outil via son chemin absolu
    C:\oracle-tools\sqlcl\bin\sql.exe $(DB_USER)/$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_SERVICE_NAME) @scripts/deploy_mfa.sql
    
    echo === Fin du processus DevOps Oracle - Succes ===
  displayName: "Déploiement du schéma SQL sur Oracle Linux"
  env:
    DB_PASSWORD: $(DB_PASSWORD)


