-- Si une erreur survient, SQLcl arrête l'exécution et renvoie le code d'erreur au pipeline
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE mfa_demande_subvention (
    id_demande NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_demandeur VARCHAR2(100) NOT NULL,
    montant_accorde NUMBER(10,2),
    date_soumission DATE DEFAULT SYSDATE
);

INSERT INTO mfa_demande_subvention (nom_demandeur, montant_accorde) 
VALUES ('Famille Tremblay', 1500.00),('Famille Côté', 2500.00) ;

COMMIT;
EXIT;

